AMI:
  centos-7-x86-64-west-evrt:
    :image:
      :pe: ami-34a92954
    :region: us-west-2
    :availability_zone: us-west-2c
  centos-7-x86-64-west-fldr:
    :image:
      :pe: ami-34a92954
    :region: us-west-2
    :availability_zone: us-west-2b
